version: "3.3"

services:
  santedb-postgres:
    image: postgres
    environment:
      POSTGRES_USER: santedb
      POSTGRES_PASSWORD: santedb
    volumes:
      - "santedb-postgres-data:/var/lib/postgresql/data"

  santedb-mpi:
    image: santesuite/santedb-mpi:latest
    environment:
      - SDB_FEATURE=LOG;DATA_POLICY;AUDIT_REPO;ADO;PUBSUB_ADO;RAMCACHE;SEC;SWAGGER;OPENID;FHIR;HL7;HDSI;AMI;BIS;MDM;MATCHING;IHE_PIXM;IHE_PDQM;IHE_PMIR;IHE_PIX;IHE_PDQ
      # HL7v2 Messages should use MSH-8 secrets for authentication
      - SDB_HL7_AUTHENTICATION=Msh8
      # Matching mode should be weighted (alternate is SIMPLE)
      - SDB_MATCHING_MODE=WEIGHTED
      # Resources under MDM control:
      #   - Patient
      - SDB_MDM_RESOURCE=Patient
      # Primary database connection string for CDR data
      - SDB_DB_MAIN=server=santedb-postgres;port=5432; database=santedb; user id=santedb; password=santedb; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
      # Database connection for audit repository
      - SDB_DB_AUDIT=server=santedb-postgres;port=5432; database=auditdb; user id=santedb; password=santedb; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
      # ADO provider for main database
      - SDB_DB_MAIN_PROVIDER=Npgsql
      # ADO provider for audit database
      - SDB_DB_AUDIT_PROVIDER=Npgsql
      # When sensitive data is being disclosed - hide it
      # Other options are:
      #   Audit -> Disclose and raise an audit
      #   None -> Take no action
      #   Redact -> Redact/censor the information
      - SDB_DATA_POLICY_ACTION=HIDE
      # Wait 5 seocnds for database to become available before starting up
      - SDB_DELAY_START=5000
    depends_on:
      - santedb-postgres
    volumes:
         - santedb-data:/santedb

  santedb-www:
    image: santesuite/santedb-www:latest
    depends_on:
      - santedb-mpi
  # deploy:
  #     placement:
  #       constraints:
  #         - "node.labels.name==node-3"

volumes: 
  santedb-data:
  santedb-postgres-data:
